# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "parallel"
batch_size_run: 1
mac: "ccdg_comm_mac"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent: "rnn" # Default rnn agent
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32

name: "ccdg_smac"

atom: 51
vmin: -10
vmax: 10

# Comm
comm: True
comm_embed_dim: 10
comm_method: "ccdg"

only_downstream: True
use_IB: False

signature_dim: 32

is_cur_mu: True
#True 消融超参数
rho: 0
BAT: 1
H: 10000
