env: shapes

env_args:
    obs_last_action: False
    state_last_action: True
    reward_win: 200
    is_print: False
    debug: False
    num_agents: 4
    sight_range: 3
    obs_coordinates: False
    obs_time_step: False
    obs_goals: False
    obs_agent_ids: True
    normalize: True
    step_size: 1
    fix_spawn: False
    fix_image: False
    split: 'train.large'  # train.med, train.small, train.tiny, val, test
    task: 'colors.4,0,0'
    episode_limit: 30

learner_log_interval: 20000
log_interval: 20000
runner_log_interval: 20000
t_max: 10050000
test_interval: 20000
test_nepisode: 24
test_greedy: True